-- Migration 002: Add AI Agent Fields to mood_logs table
-- This migration adds support for the three AI agents:
-- 1. Analyzer Agent: primary_emotion, summary
-- 2. Empathy Agent: ai_feedback (already exists)
-- 3. Avatar Orchestrator: avatar_state

-- Add primary_emotion column
ALTER TABLE mood_logs 
ADD COLUMN IF NOT EXISTS primary_emotion VARCHAR(50);

-- Add summary column
ALTER TABLE mood_logs 
ADD COLUMN IF NOT EXISTS summary TEXT;

-- Add avatar_state column
ALTER TABLE mood_logs 
ADD COLUMN IF NOT EXISTS avatar_state VARCHAR(50);

-- Add comments for documentation
COMMENT ON COLUMN mood_logs.primary_emotion IS 'Primary emotion detected by Analyzer Agent (vui, buồn, giận, lo lắng, bình yên, mệt mỏi)';
COMMENT ON COLUMN mood_logs.summary IS 'One-sentence summary of emotional state generated by Analyzer Agent';
COMMENT ON COLUMN mood_logs.avatar_state IS 'Avatar state for UI (STATE_JOYFUL, STATE_NEUTRAL, STATE_SAD, STATE_EXHAUSTED, STATE_ANXIOUS)';

-- Create index on avatar_state for potential filtering/analytics
CREATE INDEX IF NOT EXISTS idx_mood_logs_avatar_state ON mood_logs(avatar_state);

-- Create index on primary_emotion for analytics
CREATE INDEX IF NOT EXISTS idx_mood_logs_primary_emotion ON mood_logs(primary_emotion);
